### ISSUE TITLE
coapy hangs, no output

### ISSUE THREAD

**Issue by vscooper** [Andrew-S-Rosen/coapy#7]
Hi, I love the goal here but it hasn't worked for me. Created a new environment with python 3.11, installed successfully, and ran 
`from coapy.scholar import get_coauthors

scholar_id = "dcezvIQAAAAJ" # Google Scholar ID
my_coauthors = get_coauthors(scholar_id=scholar_id, years_back=4)
print(my_coauthors)`

with no output. Guidance appreciated!

**Comment by Andrew-S-Rosen** [comment]
Huh! What do you know. It sure does...

I think technically it's working but there is some massive slowdown somewhere, clearly. I'll have to look into this when I'm not scrambling to get an NSF proposal done, which is what prompted me to check this issue tracker this evening. 😅 Thanks for the report!

**Comment by Andrew-S-Rosen** [comment]
Looks like it works but it's just slow on the querying. I added a progress bar to the code so users know what's going on. In your instance, it tries to fetch the details of 202 entries, and it takes a little over a second per publication query. Partway through, it gets slower (probably because Google Scholar imposes some sort of rate-limiting), so it ultimately ends up taking several minutes. A bit annoying. I'm going to close this issue and re-open one about speeding it up.
